const express = require('express');
const router = express.Router();
const controller = require('../controllers/user.controller');
const isAuthenticated = require('../middlewares/auth.middleware');
router.post('/users', controller.createUser);
router.post('/login', controller.login);
router.use(isAuthenticated);
router.get('/users', controller.getUsers);
router.get('/users/:id', controller.getUserById);
module.exports = router;